apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-cm
  name: deploy-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-cm
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-cm
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          envFrom:
          - configMapRef:
              name: db-env
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 3
            httpGet:
              path: /
              port: 80
