apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web-replicaset
    spec:
      containers:
        - name: web-container
          image: felipedds/telegram-yfinance:1.0
          ports:
            - containerPort: 80
