apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-log-collector
spec:
  selector:
    matchLabels:
      name: daemonset-log-collector
  template:
    metadata:
      labels:
        name: daemonset-log-collector
    spec:
      nodeSelector:
        type: bigger-node
      containers:
        - name: fluentd
          image: fluentd
