apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-container
  template:
    metadata:
      labels:
        app: web-container
    spec:
      containers:
        - name: web-container
          image: felipedds/telegram-yfinance:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: web-container
spec:
  selector:
    app: web-container
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
