apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    name: my-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: run-job
              image: node:lts-jessie
              command: ["node", "job.js"]
          restartPolicy: OnFailure
  