apiVersion: batch/v1
kind: Job
metadata:
  name: runner
spec:
  parallelism: 2
  completions: 4
  template:
    spec:
      containers:
        - name: run-job
          image: nginx:1.21.5
          command: [nginx-debug, '-g', 'daemon off;']
      restartPolicy: Never
  backoffLimit: 4
